/* Proyecciones comerciales: hechos descargados, sin pedidos automáticos. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LogisticaComercial=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const numero=v=>v===null||v===undefined||String(v).trim()===''?null:Number.isFinite(Number(v))?Number(v):null;
 function catalogo(snapshot){return (snapshot?.filas||[]).map(p=>({...p,codigo:p.codigo||p.CODIGO,descripcion:p.descripcion||p.DESCRIPCION,unidad:p.unidad||p.UNIDAD||null,categoria:p.categoria||p.CATEGORIA||'',stock:numero(p.stock??p.STOCK_TEORICO),precio:numero(p.precio??p.COSTO_CLIENTE),costo:numero(p.costo??p.COSTO_PROVEEDOR),coberturaUnidad:p.UNIDAD_ORIGEN||'NO_DECLARADA'}));}
 function consumoNegocio(n,snapshot,vinculos){
  if(!snapshot)return {estado:'NO_PUBLICADO',productos:[],clienteERP:n.clienteERP||null};
  const vs=vinculos?.filas||[],v=vs.find(v=>[v.negocioId,v.id,v.uuid].includes(n.id)||n.clienteERP&&[v.clienteERP,...(v.alias||[])].includes(n.clienteERP)),clienteERP=v?.clienteERP||n.clienteERP,nombres=new Set([clienteERP,n.clienteERP,...(v?.alias||[])].filter(Boolean));
  const exactas=(snapshot.filas||[]).filter(p=>p.negocioId===n.id),productos=(exactas.length?exactas:(snapshot.filas||[]).filter(p=>nombres.has(p.clienteERP||p.cliente||p.clienteNombre)&&(!p.negocioId||[v?.negocioId,v?.id,v?.uuid].filter(Boolean).includes(p.negocioId)))).map(p=>({...p,referenciaNegocioERP:p.negocioId,negocioId:n.id,producto:p.descripcion||p.producto||p.codigo,compras:Number(p.comprasDistintas??p.compras??0)}));
  return {estado:!snapshot.completo?'INCOMPLETO':productos.some(p=>p.compras>0)?'COMPLETO':'SIN_COMPRAS',productos,clienteERP,cobertura:productos.some(p=>p.referenciaNegocioERP!==n.id)?'CLIENTE_SIN_DESGLOSE_SUCURSAL':'ESTABLECIMIENTO'};
 }
 function habito(p,hoy){const compras=Number(p.comprasDistintas??p.compras??0),intervalos=(p.intervalosDias||[]).filter(d=>Number.isFinite(d)&&d>0).sort((a,b)=>a-b),i=Math.floor(intervalos.length/2),intervalo=intervalos.length>=2?(intervalos.length%2?intervalos[i]:(intervalos[i-1]+intervalos[i])/2):null,ultima=p.ultimaCompra||p.ultima_compra,diasDesdeUltima=ultima?(Date.parse(hoy+'T12:00:00Z')-Date.parse(String(ultima).slice(0,10)+'T12:00:00Z'))/86400000:null;return {compras,media:compras>0&&numero(p.cantidad)!==null?numero(p.cantidad)/compras:null,habitual:compras>=3&&intervalo!==null,intervaloDias:intervalo,diasDesdeUltima,leToca:compras>=3&&intervalo!==null&&diasDesdeUltima>=intervalo};}
 function necesidadesEntrevista(items){return items.filter(p=>String(p.producto||'').trim()).map(p=>{const cantidad=numero(p.cantidad);if(cantidad!==null&&cantidad<0)throw Error('La cantidad no puede ser negativa');if(p.confirmado&&(cantidad===null||cantidad<=0||!String(p.unidad||'').trim()))throw Error('Confirma cantidad y unidad del producto');return {...p,cantidad,fuente:p.confirmado?(['CONTACTO','VENDEDOR'].includes(p.fuente)?p.fuente:'PENDIENTE'):'PENDIENTE',cantidadConfirmada:!!p.confirmado};});}
 function estrategia(n,d){if(n.noContacto||n.archivado)return ['No sugerir contacto comercial para este negocio.'];const pasos=[];for(const c of d.contacto||[])pasos.push(`Hablar con ${c.nombre}${c.influencia?' ('+c.influencia+')':''}${c.horario?' · horario declarado: '+c.horario:''}.`);const respuestas=new Set();for(const e of [...(d.entrevista||[])].sort((a,b)=>Date.parse(b.fechaHecho)-Date.parse(a.fechaHecho)))for(const [k,t] of [['dificultad','Problema declarado'],['proyecto','Proyecto declarado'],['valora','Criterio al elegir proveedor'],['prueba','Paso aceptable para probar']])if(e[k]&&!respuestas.has(k)){respuestas.add(k);pasos.push(`${t}: ${e[k]}. Procedencia: ${e.procedencia?.[k]||e.fuente||'PENDIENTE'}.`);}const cerrados=new Set((d.compromiso||[]).map(c=>c.cierraRegistroId).filter(Boolean));for(const c of d.compromiso||[])if(!c.cierraRegistroId&&!cerrados.has(c.id))pasos.push(`Cumplir: ${c.accion}${c.fechaLimite?' · '+c.fechaLimite:''}. Responsable: ${c.responsable||'por definir'}.`);for(const p of d.necesidad||[])pasos.push(`${p.fuente==='PENDIENTE'?'Aclarar':'Revisar oferta para'} ${p.producto} · ${p.especificacion||'especificación pendiente'}. Hecho: necesidad registrada (${p.fuente||'PENDIENTE'}); confirmar disponibilidad y entrega.`);if(!d.contacto?.length)pasos.push('Averiguar quién solicita y quién autoriza la compra, y cuándo puede atender.');return pasos;}
 return {catalogo,consumoNegocio,habito,necesidadesEntrevista,estrategia};
});
