(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LogisticaMetricas=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 function cuota({usado=0,limite,tarifaPorMil=0,ultimoConteo=null}={}){if(!Number.isFinite(limite)||limite<=0||!Number.isFinite(usado)||usado<0||!Number.isFinite(tarifaPorMil)||tarifaPorMil<0)throw Error('Cuota inválida');const porcentaje=usado/limite*100;return {usado,limite,porcentaje,nivel:porcentaje>=90?'ROJO':porcentaje>=70?'AMARILLO':'NORMAL',requiereConfirmacion:porcentaje>=100,costoEstimado:Math.max(0,usado-limite)/1000*tarifaPorMil,ultimoConteo,rotulo:'Estimación de la app; cargo real en consola del proveedor'};}
 function dia(valor){const v=String(valor||'');if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;if(!v.includes('T')||!/(Z|[+-]\d\d:\d\d)$/.test(v)||!Number.isFinite(Date.parse(v)))return '';const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Tijuana',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(v)).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}`;}
 const fecha=e=>e.fechaHecho||e.fecha||e.ts||'';
 function dentroPeriodo(e,desde,hasta){const d=dia(fecha(e));return !!d&&d>=desde&&d<=hasta;}
 const ratio=(numerador,denominador)=>({numerador,denominador,porcentaje:denominador?numerador/denominador*100:null});
 const numero=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
 const unicos=filas=>[...new Map(filas.map((e,i)=>[e.id??`sin-id-${i}`,e])).values()];
 function semana(d){const f=new Date(d+'T12:00:00Z');f.setUTCDate(f.getUTCDate()-(f.getUTCDay()+6)%7);return f.toISOString().slice(0,10);}
 function resumir({desde,hasta,visitas=[],documentos=[],rutas=[],compromisos=[],negocios=[],vinculos=[],contactos=[],necesidades=[],propuestas=[],cargas=[],eventos=[],consumo=null,planSemana=[]}={}){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(desde||'')||!/^\d{4}-\d{2}-\d{2}$/.test(hasta||'')||desde>hasta)throw Error('Período inválido');
  const dentro=e=>dentroPeriodo(e,desde,hasta),antes=e=>dia(fecha(e))&&dia(fecha(e))<=hasta;
  const vs=unicos(visitas).filter(dentro),presenciales=vs.filter(v=>v.canal==='PRESENCIAL'),ns=new Map(negocios.map(n=>[n.id,n]));
  // Un UUID oficial puede corresponder a un expediente local; nunca elegir una sucursal por azar.
  const aliases=new Map();for(const n of negocios){const id=n.id;if(!id)continue;for(const a of [n.clienteERP,n.clienteNombre,...(Array.isArray(n.alias)?n.alias:[])]){if(!a)continue;const ids=aliases.get(a)||new Set();ids.add(id);aliases.set(a,ids);}}
  const negocioDocumento=d=>{if(d.negocioId&&ns.has(d.negocioId))return d.negocioId;const alias=d.clienteERP||d.cliente||d.clienteNombre,ids=aliases.get(alias);if(ids){if(ids.size!==1)return null;if(d.negocioId&&!vinculos.some(v=>(v.negocioId||v.id||v.uuid)===d.negocioId&&[v.clienteERP,v.clienteNombre,...(Array.isArray(v.alias)?v.alias:[])].includes(alias)))return null;return [...ids][0];}return d.negocioId||null;};
  const docs=unicos(documentos).filter(d=>d.confirmadoERP===true&&!d.invalidadoERP&&!['ANULADA','CANCELADA'].includes(d.estado)),ds=docs.filter(dentro);
  const compras=docs.filter(d=>!Array.isArray(d.items)||d.items.some(i=>i.estado==='ACTIVA')).map(d=>({...d,negocioId:negocioDocumento(d)})).filter(d=>d.negocioId&&antes(d)).sort((a,b)=>dia(fecha(a)).localeCompare(dia(fecha(b))));
  const porComprador=new Map();for(const d of compras){const g=porComprador.get(d.negocioId)||[];g.push(d);porComprador.set(d.negocioId,g);}
  const contactados=new Set(vs.map(v=>v.negocioId).filter(Boolean)),compraron=new Set(compras.filter(dentro).map(d=>d.negocioId));let primeraObservada=0,recompra=0;const duraciones=[];
  for(const [id,g] of porComprador){const primera=g[0];if(dentro(primera)){primeraObservada++;const inicio=visitas.filter(v=>v.negocioId===id&&dia(fecha(v))&&dia(fecha(v))<=dia(fecha(primera))).map(v=>dia(fecha(v))).sort()[0];if(inicio)duraciones.push((Date.parse(dia(fecha(primera)))-Date.parse(inicio))/86400000);}if(g.filter(dentro).some(d=>d!==primera))recompra++;}
  const originales=unicos(compromisos).filter(c=>!c.cierraRegistroId&&!c.seguimientoCerradoId&&(dentro(c)||c.fechaLimite>=desde&&c.fechaLimite<=hasta)),cerrados=new Set(compromisos.filter(c=>c.cierraRegistroId&&c.estado==='CUMPLIDO'&&antes(c)).map(c=>c.cierraRegistroId));
  const cs={cumplidos:originales.filter(c=>cerrados.has(c.id)||c.estado==='CUMPLIDO').length,vencidos:originales.filter(c=>!cerrados.has(c.id)&&c.estado!=='CUMPLIDO'&&c.fechaLimite&&c.fechaLimite<hasta).length,denominador:originales.length};
  const propuestasCorte=unicos(propuestas).filter(antes),sustituidas=new Set(propuestasCorte.map(p=>p.corrigeRegistroId).filter(Boolean));
  const decisores=new Set([...unicos(contactos).filter(c=>dentro(c)&&['COMPRA','AUTORIZA'].includes(c.influencia)).map(c=>c.negocioId),...vs.filter(v=>v.decisorCompras===true).map(v=>v.negocioId)]),necesidadesPeriodo=unicos(necesidades).filter(dentro),entregadas=propuestasCorte.filter(p=>!sustituidas.has(p.id)&&dentro(p)&&(p.estado==='ENTREGADA'||p.entregada===true));
  rutas=unicos(rutas).map(r=>{const plan=unicos(eventos).filter(e=>e.rutaId===r.id&&e.tipo==='REPLANIFICACION'&&antes(e)).sort((a,b)=>Date.parse(fecha(b))-Date.parse(fecha(a)))[0];return plan?{...r,orden:plan.orden,paradas:plan.paradas,agenda:plan.agenda,planeadas:plan.orden.length}:r;});
  const rs=unicos(rutas).filter(dentro),es=unicos(eventos).sort((a,b)=>Date.parse(fecha(a))-Date.parse(fecha(b))),tareas=new Map();for(const r of rutas)for(const p of r.paradas||[])for(const t of p.tareas||[])tareas.set(t.id,{...t,rutaId:r.id,paradaId:p.id});
  const resultadoTarea=new Map();for(const e of es.filter(dentro))if(e.tipo==='RESULTADO'&&tareas.has(e.tareaId))resultadoTarea.set(e.tareaId,e);
  const conteoTarea=(tipo,completo,no)=>{const planeadas=[...tareas.values()].filter(t=>t.tipo===tipo&&rs.some(r=>r.id===t.rutaId)),resultados=[...resultadoTarea.values()].filter(e=>tareas.get(e.tareaId).tipo===tipo),bien=resultados.filter(e=>e.resultado===completo);return {planeadas:planeadas.length,registradas:resultados.length,completas:bien.length,parciales:resultados.filter(e=>e.resultado==='PARCIAL').length,noRealizadas:resultados.filter(e=>e.resultado===no).length,pendientes:planeadas.filter(t=>!resultadoTarea.has(t.id)).length,motivos:resultados.filter(e=>e.resultado===no).map(e=>e.motivo||'Sin motivo registrado'),aTiempo:ratio(bien.filter(e=>e.aTiempo===true).length,bien.filter(e=>typeof e.aTiempo==='boolean').length),aLaPrimera:ratio(bien.filter(e=>e.primerIntento===true).length,bien.filter(e=>typeof e.primerIntento==='boolean').length)};};
  const cobros=[...tareas.values()].filter(t=>t.tipo==='COBRANZA'&&rs.some(r=>r.id===t.rutaId)),pagos=es.filter(e=>dentro(e)&&e.tipo==='PAGO_CONFIRMADO'&&e.publicadoERP===true&&numero(e.importe)&&cobros.some(t=>t.id===e.tareaId)),saldoConocido=cobros.filter(t=>numero(t.saldo));
  let traslado=0,parada=0,tramosMedidos=0,paradasMedidas=0,tramosExcluidos=0;
  for(const r of rutas){let salida=r.fechaHecho?{ts:r.fechaHecho}:null,llegada=null,pausa=false;for(const e of es.filter(e=>e.rutaId===r.id)){
   if(['PAUSA','DESVIO'].includes(e.tipo)){pausa=true;continue;}
   if(e.tipo==='LLEGADA'){if(salida){const min=(Date.parse(fecha(e))-Date.parse(fecha(salida)))/60000;if(dentro(salida)&&dentro(e)&&min>=0&&Number.isFinite(min)&&!pausa){traslado+=min;tramosMedidos++;}else if(dentro(e))tramosExcluidos++;}llegada=e;salida=null;pausa=false;}
   if(e.tipo==='SALIDA'){if(llegada&&e.paradaId===llegada.paradaId){const min=(Date.parse(fecha(e))-Date.parse(fecha(llegada)))/60000;if(dentro(llegada)&&dentro(e)&&min>=0&&Number.isFinite(min)){parada+=min;paradasMedidas++;}}salida=e;llegada=null;pausa=false;}
   if(e.tipo==='CIERRE'&&salida){const min=(Date.parse(fecha(e))-Date.parse(fecha(salida)))/60000;if(dentro(salida)&&dentro(e)&&min>=0&&Number.isFinite(min)&&!pausa){traslado+=min;tramosMedidos++;}else if(dentro(e))tramosExcluidos++;salida=null;}
  }}
  const realizadasRuta=r=>{const salidas=es.filter(e=>e.rutaId===r.id&&e.tipo==='SALIDA'&&dentro(e)&&e.paradaId);return salidas.length?new Set(salidas.map(e=>e.paradaId)).size:numero(r.realizadas)?r.realizadas:0;};
  const semanal=new Map(),sem=d=>{const s=semana(d);if(!semanal.has(s))semanal.set(s,{semana:s,planeadas:0,realizadas:0,salidas:0,fuentePlan:'Rutas registradas'});return semanal.get(s);};for(const r of rs){const s=sem(dia(fecha(r)));s.planeadas+=r.planeadas??r.orden?.length??0;s.realizadas+=realizadasRuta(r);s.salidas++;}
  const planes=(Array.isArray(planSemana)?planSemana:planSemana?.dias||[]).filter(p=>dentro({fecha:p.fecha}));for(const s of new Set(planes.map(p=>semana(p.fecha)))){const v=sem(s);v.planeadas=0;v.fuentePlan='Plan semanal guardado';}for(const p of planes)sem(p.fecha).planeadas+=(p.paradas||[]).length;
  const agrupar=clave=>{const g=new Map();for(const v of vs){const valor=clave==='vendedor'?v.vendedorId||'Sin vendedor asignado':ns.get(v.negocioId)?.[clave]||'Sin dato';if(!g.has(valor))g.set(valor,{valor,contactos:0,visitas:0,negocios:new Set(),compraron:new Set()});const a=g.get(valor);a.contactos++;if(v.canal==='PRESENCIAL')a.visitas++;a.negocios.add(v.negocioId);if(compraron.has(v.negocioId))a.compraron.add(v.negocioId);}return [...g.values()].map(g=>({...g,negocios:g.negocios.size,compraron:g.compraron.size}));};
  const motivos=new Map();for(const v of vs)if(v.resultado)motivos.set(v.resultado,(motivos.get(v.resultado)||0)+1);const importes=ds.filter(d=>numero(d.total)&&(!d.moneda||d.moneda==='MXN'));
  return {periodo:{desde,hasta,zonaHoraria:'America/Tijuana'},visitas:presenciales.length,contactos:vs.length,negociosUnicos:new Set(presenciales.map(v=>v.negocioId)).size,documentos:ds.length,compradoresContactados:new Set(vs.filter(v=>v.decisorCompras===true).map(v=>v.negocioId)).size,compradoresIdentificados:decisores.size,compromisos:cs,
   necesidades:{total:necesidadesPeriodo.length,fueraCatalogo:necesidadesPeriodo.filter(n=>!n.codigo).length,fueraCatalogoDetalle:necesidadesPeriodo.filter(n=>!n.codigo).map(n=>({producto:n.producto,especificacion:n.especificacion,negocio:ns.get(n.negocioId)?.nombre||'Sin negocio identificado',cantidad:n.cantidad,unidad:n.unidad,fuente:n.fuente||'PENDIENTE'})),fuentes:Object.fromEntries(['CONTACTO','VENDEDOR','PENDIENTE'].map(f=>[f,necesidadesPeriodo.filter(n=>n.fuente===f).length]))},avance:{propuestasEntregadas:entregadas.filter(p=>p.tipo!=='MUESTRA').length,cotizacionesEntregadas:entregadas.filter(p=>p.tipo==='COTIZACION').length,muestrasEntregadas:entregadas.filter(p=>p.tipo==='MUESTRA').length+unicos(cargas).filter(c=>dentro(c)&&c.tipo==='MUESTRA'&&c.entregada===true&&!entregadas.some(p=>p.id===c.propuestaId)).length},
   compras:{primeraObservada,recompra,rotulo:'Primera compra observada; no acredita primera compra histórica',contactadosCompraron:ratio([...contactados].filter(id=>compraron.has(id)).length,contactados.size),tiempoHastaPrimera:{promedioDias:duraciones.length?duraciones.reduce((a,b)=>a+b,0)/duraciones.length:null,denominador:duraciones.length},sinVinculo:ds.filter(d=>!negocioDocumento(d)).length},importeVentas:{importe:importes.length?importes.reduce((s,d)=>s+d.total,0):null,denominador:importes.length,documentos:ds.length,moneda:'MXN',rotulo:'Total publicado ERP, incluye IVA; no utilidad ni cobranza'},
   paradas:ratio(rs.reduce((s,r)=>s+realizadasRuta(r),0),rs.reduce((s,r)=>s+(r.planeadas??r.orden?.length??0),0)),entregas:conteoTarea('ENTREGA','ENTREGADA','NO_ENTREGADA'),recolecciones:conteoTarea('RECOLECCION','RECOGIDA','NO_RECOGIDA'),
   cobranza:{programadas:cobros.length,programado:saldoConocido.length?saldoConocido.reduce((s,t)=>s+t.saldo,0):null,saldosPublicados:saldoConocido.length,relatosPorConfirmar:[...resultadoTarea.values()].filter(e=>tareas.get(e.tareaId).tipo==='COBRANZA'&&['COBRO','COBRO_PARCIAL'].includes(e.resultado)).length,importeConfirmado:pagos.length?pagos.reduce((s,p)=>s+p.importe,0):null,confirmaciones:pagos.length,rotulo:'Sólo aplicaciones con importe explícito confirmado por ERP; COBRO no aplica dinero'},
   tiempos:{traslado,parada,tramosMedidos,paradasMedidas,tramosExcluidos,rotulo:'Pares completos de marcas en el período; traslado con pausa/desvío se excluye. No incluye intervalos sin marcas ni fracciones fuera del período'},semanal:[...semanal.values()].sort((a,b)=>a.semana.localeCompare(b.semana)),porZona:agrupar('zona'),porGiro:agrupar('giro'),porVendedor:agrupar('vendedor'),motivos:[...motivos].map(([motivo,total])=>({motivo,total})),
   cobertura:{estado:consumo?.estado||'NO_PUBLICADO',completo:consumo?.completo===true,periodo:consumo?.periodo||null,publicadoTs:consumo?.capturadoTs||consumo?.publicadoTs||consumo?.publicadoEn||null,historiaCompleta:false,rotulo:'Datos disponibles en este teléfono. Snapshot completo cubre su período, no toda la historia; cohortes con distinto seguimiento no son comparables'},procedencia:'Contactos/visitas y evidencias capturadas; documentos confirmados ERP; eventos de ruta y plan guardado. Autor identificado por el teléfono vinculado',atribucion:'Coincidencia de expediente (UUID o alias inequívoco), contacto y compra en el mismo período; sin atribución causal. Tiempo desde primer contacto registrado hasta primera compra observada, días de calendario Tijuana'};
 }
 return {cuota,resumir,dentroPeriodo,dia};
});
