(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LogisticaPreparacion=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';const key=p=>`${p.codigo||p.producto||''}|${p.unidad||''}`;const qty=q=>Number.isFinite(q)&&q>=0?q:0;
 function intervaloCompra(fechas,ahora){const fs=[...new Set(fechas)].map(Date.parse).filter(Number.isFinite).sort((a,b)=>a-b);if(fs.length<3)return {suficiente:false,razon:'Se requieren al menos tres compras distintas confirmadas'};const intervalos=fs.slice(1).map((f,i)=>(f-fs[i])/86400000).sort((a,b)=>a-b),i=Math.floor(intervalos.length/2),intervaloDias=intervalos.length%2?intervalos[i]:(intervalos[i-1]+intervalos[i])/2,diasDesdeUltima=(Date.parse(ahora)-fs.at(-1))/86400000;return {suficiente:true,intervaloDias,diasDesdeUltima,leToca:diasDesdeUltima>=intervaloDias,procedencia:'Compras confirmadas ERP; sugerencia, no pedido'};}
 function preparar(input={}){const ids=new Set((input.negocios||[]).map(n=>n.id)),estadoConsumo=input.consumo?.estado||'NO_PUBLICADO',items=[];
  if(estadoConsumo==='COMPLETO')for(const p of input.consumo.productos||[])if(ids.has(p.negocioId)&&p.compras>0&&typeof p.cantidad==='number'&&Number.isFinite(p.cantidad))items.push({...p,cantidad:qty(p.cantidad)/p.compras,fuente:'COMPRA_CONFIRMADA'});
  for(const p of input.necesidades||[])if(ids.has(p.negocioId)&&p.fuente!=='PENDIENTE'&&p.cantidadConfirmada!==false&&Number(p.cantidad)>0)items.push({...p,cantidad:qty(p.cantidad),fuente:p.fuente==='VENDEDOR'?'ESTIMADO_VENDEDOR':'DICHO_CONTACTO'});
  const grupos=new Map();for(const p of items){const k=key(p);if(!grupos.has(k))grupos.set(k,{codigo:p.codigo,producto:p.producto,unidad:p.unidad,cantidad:0,destinatarios:[]});const g=grupos.get(k);g.cantidad+=p.cantidad;g.destinatarios.push({negocioId:p.negocioId,cantidad:p.cantidad,fuente:p.fuente});}
  const materiales=[...grupos.values()].map(g=>{const s=(input.stock||[]).find(p=>key(p)===key(g)),enCatalogo=(input.catalogo||[]).some(p=>p.codigo===g.codigo);return {...g,enCatalogo,existenciaTeorica:s?.cantidad??null,stockPublicadoEn:input.stockPublicadoEn||null,antiguedadDias:input.stockPublicadoEn&&input.ahora?(Date.parse(input.ahora)-Date.parse(input.stockPublicadoEn))/86400000:null,insuficiente:s?g.cantidad>s.cantidad:null,disponibilidadGarantizada:false};});
  return {estadoConsumo,materiales:materiales.filter(p=>p.enCatalogo),fueraCatalogo:materiales.filter(p=>!p.enCatalogo),muestras:(input.muestras||[]).map(p=>({...p})),carga:(input.carga||[]).map(p=>({...p})),stockPublicadoEn:input.stockPublicadoEn||null,preparacionPendiente:materiales.filter(p=>p.insuficiente||p.existenciaTeorica==null||!p.enCatalogo).map(p=>({codigo:p.codigo,razon:!p.enCatalogo?'No lo tenemos en catálogo':p.existenciaTeorica==null?'Existencia no publicada':'Sugerencia supera existencia teórica'})),requiereConfirmacionVendedor:true};
 }
 function cuadreRegreso({carga=[],ventas=[],regreso=[],muestras=[]}={}){const consolidado=new Map();for(const c of carga){const k=key(c);if(!consolidado.has(k))consolidado.set(k,{...c,cantidad:0});consolidado.get(k).cantidad+=qty(c.cantidad);}const productos=[...consolidado.values()].map(c=>{const vendidas=ventas.filter(v=>v.confirmadoERP===true&&key(v)===key(c)).reduce((s,v)=>s+qty(v.cantidad),0),retorno=regreso.filter(r=>key(r)===key(c)).reduce((s,r)=>s+qty(r.cantidad),0);return {...c,vendidas,regreso:retorno,diferencia:qty(c.cantidad)-vendidas-retorno};});return {productos,ventasPorConfirmar:ventas.filter(v=>v.confirmadoERP!==true).map(v=>({...v})),muestras:muestras.map(p=>({...p})),requiereResolver:productos.some(p=>p.diferencia!==0),ajustaInventario:false};}
 return {intervaloCompra,preparar,cuadreRegreso};
});

