/* Carga al final de las pantallas: reemplaza resultados() sin alterar la navegación. */
'use strict';
(function(){
 const cantidad=n=>Number.isFinite(n)?new Intl.NumberFormat('es-MX',{maximumFractionDigits:1}).format(n):'No disponible';
 const dinero=n=>Number.isFinite(n)?new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n):'No disponible';
 const proporcion=r=>`${r.numerador} / ${r.denominador}${r.porcentaje==null?' · Sin base':` · ${cantidad(r.porcentaje)}%`}`;
 const panel=(titulo,contenido)=>`<section class="panel"><h2>${esc(titulo)}</h2>${contenido}</section>`;
 const tabla=(titulos,filas)=>`<div style="overflow-x:auto"><table><thead><tr>${titulos.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${filas.map(f=>`<tr>${f.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 const tareasHTML=t=>`<p>${t.completas} completas · ${t.parciales} parciales · ${t.noRealizadas} no realizadas</p><p>${t.registradas} tareas con resultado / ${t.planeadas} programadas · ${t.pendientes} sin resultado.</p><p>A tiempo: ${proporcion(t.aTiempo)}<br>A la primera: ${proporcion(t.aLaPrimera)}</p><p class="ayuda">Las proporciones usan sólo resultados con confirmación explícita de horario o primer intento.</p>${t.motivos.length?'<p>Motivos: '+t.motivos.map(esc).join('; ')+'</p>':''}`;
 resultados=async function(periodo={}){
  if(!window.logisticaAccesoPermitido()){avisar('Desbloquea el teléfono para consultar resultados');return;}
  const desde=periodo.desde||fechaHoy().slice(0,7)+'-01',hasta=periodo.hasta||fechaHoy(),entidades=['negocio','contacto','necesidad','propuesta','compromiso','ruta','evento_ruta','carga'];
  const filas=await Promise.all(entidades.map(e=>baseLocal.listar(e))),datos=Object.fromEntries(entidades.map((e,i)=>[e,filas[i]]));
  const [visitas,documentos,consumo,vinculo,planSemana]=await Promise.all([baseLocal.visitas(),documentosERP(),ultimoSnapshot('consumo'),ultimoSnapshot('vinculo'),baseLocal.meta('planSemana')]);
  const r=LogisticaMetricas.resumir({desde,hasta,visitas,documentos,consumo,vinculos:vinculo?.filas||[],planSemana,negocios:datos.negocio,contactos:datos.contacto,necesidades:datos.necesidad,propuestas:datos.propuesta,compromisos:datos.compromiso,rutas:datos.ruta,eventos:datos.evento_ruta,cargas:datos.carga});
  const fuentes=r.necesidades.fuentes,compras=r.compras,cob=r.cobranza,tiempos=r.tiempos;
  $('app').innerHTML=`<h1>Resultados</h1>${window.logisticaGoogleActivo?.()?'<section id="cuota-resultados" class="panel" aria-live="polite"><h2>Consumo de mapas y rutas</h2><p>Consultando último conteo disponible…</p></section>':''}<form id="periodo-resultados" class="panel"><div class="dos-columnas">${campo('desde','Desde','date',desde,'required')}${campo('hasta','Hasta','date',hasta,'required')}</div><button>Consultar período</button></form><p>${esc(desde)} — ${esc(hasta)} · hora de Tijuana</p><div class="resumen-cifras" role="group" aria-label="Resumen del período"><div><strong>${r.visitas}</strong><span>Visitas presenciales</span></div><div><strong>${r.negociosUnicos}</strong><span>Negocios visitados</span></div><div><strong>${r.entregas.completas}</strong><span>Entregas hechas</span></div><div><strong>${r.compromisos.vencidos}</strong><span>Compromisos vencidos</span></div></div><details class="detalle-resultados"><summary>Ver todo el detalle</summary><div class="bloques">${
   panel('Alcance y contacto',`<p>${r.visitas} visitas presenciales · ${r.negociosUnicos} negocios distintos visitados.</p><p>${r.contactos} contactos de todos los canales · ${r.compradoresContactados} negocios donde se conversó con quien decide compras.</p><p>${r.compradoresIdentificados} negocios con comprador identificado en el período.</p><p class="ayuda">Sólo la conversación marcada explícitamente cuenta como contacto con el decisor; registrar su nombre identifica al comprador.</p>`)+
   panel('Necesidades y avance',`<p>${r.necesidades.total} necesidades registradas · ${r.necesidades.fueraCatalogo} sin código del catálogo.</p><p>Dicho por contacto: ${fuentes.CONTACTO} · estimado por vendedor: ${fuentes.VENDEDOR} · pendiente: ${fuentes.PENDIENTE}.</p><p>${r.avance.propuestasEntregadas} propuestas entregadas (${r.avance.cotizacionesEntregadas} marcadas como cotización) · ${r.avance.muestrasEntregadas} muestras entregadas.</p><p class="ayuda">Sólo entrega explícita; un borrador o una muestra en la carga no cuenta como entrega.</p>`)+
   panel('Compras observadas',`<p>${compras.primeraObservada} negocios con primera compra observada · ${compras.recompra} con recompra observada.</p><p>Contactados que compraron: ${proporcion(compras.contactadosCompraron)}.</p><p>Tiempo a primera observada: ${cantidad(compras.tiempoHastaPrimera.promedioDias)} días · base ${compras.tiempoHastaPrimera.denominador} negocios con contacto previo.</p><p>${r.documentos} documentos confirmados; ${compras.sinVinculo} sin expediente inequívoco.</p><p>Total publicado: ${dinero(r.importeVentas.importe)} · base ${r.importeVentas.denominador} / ${r.importeVentas.documentos} documentos con total MXN.</p><p class="ayuda">${esc(compras.rotulo)}. ${esc(r.importeVentas.rotulo)}.</p>`)+
   panel('Compromisos',`<p>${r.compromisos.cumplidos} cumplidos · ${r.compromisos.vencidos} vencidos / ${r.compromisos.denominador} compromisos creados o con vencimiento en el período.</p><p class="ayuda">Cierres conocidos al final del período; vencido significa fecha límite anterior al corte.</p>`)+
   panel('Entregas',tareasHTML(r.entregas))+panel('Recolecciones',tareasHTML(r.recolecciones))+
   panel('Cobranza',`<p>${cob.programadas} tareas programadas · saldo publicado al planear: ${dinero(cob.programado)} (${cob.saldosPublicados} con importe).</p><p>Importe aplicado confirmado por ERP: ${dinero(cob.importeConfirmado)} · ${cob.confirmaciones} confirmaciones con importe.</p><p>${cob.relatosPorConfirmar} relatos de cobro por confirmar.</p><p class="ayuda">${esc(cob.rotulo)}. El saldo de la remisión puede cambiar; no es evidencia de lo cobrado en esta ruta.</p>`)+
   panel('Aprovechamiento de las salidas',`<p>Paradas cerradas / planeadas: ${proporcion(r.paradas)}.</p><p>Traslado medido: ${cantidad(tiempos.traslado)} min (${tiempos.tramosMedidos} tramos) · en parada: ${cantidad(tiempos.parada)} min (${tiempos.paradasMedidas} pares).</p><p>${tiempos.tramosExcluidos} tramos con marcas incompletas, pausa o fuera del período.</p><p class="ayuda">${esc(tiempos.rotulo)}. El traslado planeado sigue siendo una estimación del plan de salida.</p>`)
  }</div>${panel('Demanda sin código del catálogo',r.necesidades.fueraCatalogoDetalle.length?tabla(['Producto','Especificación','Negocio','Cantidad declarada','Fuente'],r.necesidades.fueraCatalogoDetalle.map(n=>[n.producto,n.especificacion||'Por confirmar',n.negocio,`${n.cantidad??'Sin cantidad'} ${n.unidad||'Sin unidad'}`,n.fuente]))+'<p class="ayuda">Fuera de catálogo o referencia pendiente; confirmar equivalencia antes de comprar.</p>':'<p>Sin solicitudes registradas sin código en el período.</p>')}${panel('Plan y realidad por semana',r.semanal.length?tabla(['Lunes de semana','Planeadas','Realizadas','Salidas','Base del plan'],r.semanal.map(s=>[s.semana,s.planeadas,s.realizadas,s.salidas,s.fuentePlan])):'<p>Sin plan ni rutas en este período.</p>')}${
   [['Zona',r.porZona],['Giro',r.porGiro],['Vendedor',r.porVendedor]].map(([titulo,filas])=>panel(titulo,filas.length?tabla([titulo,'Contactos','Presenciales','Negocios','Con compra'],filas.map(f=>[f.valor,f.contactos,f.visitas,f.negocios,f.compraron])):'<p>Sin contactos en el período.</p>')).join('')
  }${panel('Motivos de avance y estancamiento',r.motivos.length?r.motivos.map(m=>`<p>${esc(LogisticaAlmacen.RESULTADOS[m.motivo]||m.motivo)}: ${m.total}</p>`).join(''):'<p>Sin resultados de contacto registrados.</p>')}${panel('Procedencia y cobertura',`<p>Consumo ERP: ${esc(r.cobertura.estado)} · ${r.cobertura.completo?'completo para su período':'cobertura incompleta o no publicada'}.</p><p>Período publicado: ${esc(r.cobertura.periodo?.desde||'No disponible')} — ${esc(r.cobertura.periodo?.hasta||'No disponible')} · corte ${esc(r.cobertura.publicadoTs||'No disponible')}.</p><p>${esc(r.cobertura.rotulo)}.</p><p>${esc(r.procedencia)}.</p><p>${esc(r.atribucion)}.</p><p class="ayuda">Un mismo negocio puede aparecer en varios vendedores o canales; esas filas no se suman como compradores únicos.</p>`)}</details>`;
  $('periodo-resultados').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));resultados(d).catch(e=>avisar(e.message));};
  try{if(!$('cuota-resultados'))return;const html=window.logisticaCuotaHTML?await window.logisticaCuotaHTML(true):'<h2>Consumo de mapas y rutas</h2><p>Conteo no disponible; conecta el servidor comercial.</p>';if($('cuota-resultados'))$('cuota-resultados').innerHTML='<h2>Consumo de mapas y rutas</h2>'+html;}catch(e){if($('cuota-resultados'))$('cuota-resultados').innerHTML='<h2>Consumo de mapas y rutas</h2><p>Conteo no disponible. '+esc(e.message)+'</p>';}
 };
})();
