(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LogisticaRutas=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const clave=(a,b)=>`${a.id}>${b.id}`;
 function distancia(a,b){if(![a.lat,a.lon,b.lat,b.lon].every(Number.isFinite))return Infinity;const rad=x=>x*Math.PI/180;const h=Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lon-a.lon)/2)**2;return 6371000*2*Math.asin(Math.sqrt(Math.min(1,h)));}
 const mediana=xs=>{const s=xs.slice().sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2;};
 function crearMatriz(puntos,opciones={}){
  const c={umbralMedidoMetros:100,factorRecta:1.5,velocidadKmh:25,...opciones.config},pares={},missingPairs=[];
  if(c.velocidadKmh<=0||c.factorRecta<1||c.umbralMedidoMetros<0)throw Error('Configuración de tiempos inválida');
  const ps=[...new Map(puntos.map(p=>[p.id,p])).values()];
  for(const a of ps)for(const b of ps){const k=clave(a,b);if(a.id===b.id){pares[k]={minutos:0,metros:0,fuente:'MISMO_PUNTO'};continue;}
   const valid=(r,threshold)=>r.origen?.id===a.id&&r.destino?.id===b.id&&Number.isFinite(r.minutos)&&r.minutos>=0&&distancia(a,r.origen)<=threshold&&distancia(b,r.destino)<=threshold;
   const ms=(opciones.mediciones||[]).filter(r=>!r.descartada&&r.dia===opciones.dia&&r.franja===opciones.franja&&valid(r,c.umbralMedidoMetros));
   if(ms.length){pares[k]={minutos:mediana(ms.map(r=>r.minutos)),fuente:'MEDIDO',mediciones:ms.length};continue;}
   const es=(opciones.estimados||[]).filter(r=>r.fuente==='ORS'&&valid(r,0)).sort((a,b)=>String(b.ts||'').localeCompare(String(a.ts||'')));
   if(es.length){pares[k]={minutos:es[0].minutos,metros:es[0].metros,fuente:'ESTIMADO',ts:es[0].ts};continue;}
   const metros=distancia(a,b)*c.factorRecta;pares[k]={minutos:metros/1000/c.velocidadKmh*60,metros,fuente:'APROXIMADO',rotulo:'Línea recta con factor; sin tráfico'};missingPairs.push({clave:k,origen:{...a},destino:{...b}});
  }return {pares,missingPairs};
 }
 function unirParadas(paradas){const map=new Map();for(const p of paradas){if(!p.id)throw Error('Parada sin identificador');if(!map.has(p.id))map.set(p.id,{...p,tareas:[]});const v=map.get(p.id);v.tareas=[...new Map([...v.tareas,...(p.tareas||[])].map(t=>[t.id,t])).values()];if(p.cita!=null){if(v.cita!=null&&v.cita!==p.cita)throw Error(`Citas incompatibles para ${p.id}`);v.cita=p.cita;}if(p.ventana){v.ventana={desde:Math.max(v.ventana?.desde??0,p.ventana.desde??0),hasta:Math.min(v.ventana?.hasta??1440,p.ventana.hasta??1440)};}v.duracion=Math.max(v.duracion??0,p.duracion??0);}return [...map.values()];}
 function prepararInput(input){const ps=unirParadas(input.paradas||[]),tope=Math.min(10,input.config?.topeParadas??10);if(ps.length>tope)return {error:`La salida supera el tope de ${tope} paradas`};if(!input.inicio?.id||!input.fin?.id)return {error:'Falta inicio o destino final'};if(!Number.isFinite(input.horaInicio)||!Number.isFinite(input.minutosDisponibles)||input.minutosDisponibles<0)return {error:'Horario o tiempo disponible inválido'};if(ps.some(p=>p.noContacto))return {error:'Hay una parada con no contacto'};if(ps.some(p=>(p.cita!=null&&!Number.isFinite(p.cita))||(p.ventana?.desde!=null&&!Number.isFinite(p.ventana.desde))||(p.ventana?.hasta!=null&&!Number.isFinite(p.ventana.hasta))))return {error:'Cita o ventana inválida'};if(ps.some(p=>!Number.isFinite(p.duracion??0)||(p.duracion??0)<0))return {error:'Duración de visita inválida'};return {ps};}
 function tramo(input,a,b){if(a.id===b.id)return {minutos:0,fuente:'MISMO_PUNTO'};return input.matriz?.pares?.[clave(a,b)]||{minutos:Infinity,fuente:'SIN_DATO'};}
 function avanzar(input,desde,p,hora){const t=tramo(input,desde,p),margen=['ESTIMADO','APROXIMADO'].includes(t.fuente)?input.config?.margenCitaMinutos??15:0,llegada=hora+t.minutos;let comienzo=Math.max(llegada,p.ventana?.desde??0);if(p.cita!=null){if(p.cita<(p.ventana?.desde??0))return {error:'Cita fuera de ventana de '+p.id};if(llegada+margen>p.cita)return {error:`No se alcanza cita de ${p.id} a ${p.cita}`};comienzo=p.cita;}const salida=comienzo+(p.duracion??0);if(salida+(p.ventana?.hasta!=null?margen:0)>(p.ventana?.hasta??Infinity))return {error:`Ventana insuficiente en ${p.id}`};if(!Number.isFinite(salida))return {error:`Falta tiempo de traslado ${desde.id} → ${p.id}`};return {llegada,comienzo,salida,minutosTraslado:t.minutos,fuente:t.fuente,horarioSinConfirmar:!p.ventana&&p.cita==null};}
 function validarOrden(input){const prep=prepararInput(input);if(prep.error)return {viable:false,razones:[prep.error]};const ids=input.orden||prep.ps.map(p=>p.id);if(ids.length!==prep.ps.length||new Set(ids).size!==ids.length||ids.some(id=>!prep.ps.some(p=>p.id===id)))return {viable:false,razones:['El orden debe incluir cada parada una vez']};let hora=input.horaInicio,ultimo=input.inicio,traslado=0;const agenda=[];for(const id of ids){const p=prep.ps.find(p=>p.id===id),step=avanzar(input,ultimo,p,hora);if(step.error)return {viable:false,razones:[step.error]};agenda.push({paradaId:id,...step});hora=step.salida;traslado+=step.minutosTraslado;ultimo=p;}const final=tramo(input,ultimo,input.fin);hora+=final.minutos;traslado+=final.minutos;if(hora>input.horaInicio+input.minutosDisponibles)return {viable:false,razones:['Tiempo disponible insuficiente incluyendo destino final']};return {viable:true,orden:ids,agenda,horaFin:hora,minutosTraslado:traslado,razones:[]};}
 function planificar(input){const prep=prepararInput(input);if(prep.error)return {viable:false,razones:[prep.error]};let mejor=null;const razones=new Set(),ps=prep.ps,limit=input.config?.maxEstados??250000;let estados=0;
  // Branch and bound keeps appointments immutable. Budget exhaustion is visible.
  function buscar(ultimo,hora,coste,restantes,orden){if(++estados>limit)return;if(mejor&&coste>=mejor.minutosTraslado)return;if(!restantes.length){const candidate=validarOrden({...input,orden});if(candidate.viable&&(!mejor||candidate.minutosTraslado<mejor.minutosTraslado))mejor=candidate;else candidate.razones.forEach(r=>razones.add(r));return;}
   for(const p of restantes.slice().sort((a,b)=>(a.cita??a.ventana?.hasta??Infinity)-(b.cita??b.ventana?.hasta??Infinity)||tramo(input,ultimo,a).minutos-tramo(input,ultimo,b).minutos)){const s=avanzar(input,ultimo,p,hora);if(s.error){razones.add(s.error);continue;}if(s.salida>input.horaInicio+input.minutosDisponibles){razones.add('Tiempo disponible insuficiente');continue;}buscar(p,s.salida,coste+s.minutosTraslado,restantes.filter(q=>q.id!==p.id),[...orden,p.id]);}
  }buscar(input.inicio,input.horaInicio,0,ps,[]);return mejor?{...mejor,optimo:estados<=limit,estados}: {viable:false,razones:[...razones,...(estados>limit?['Búsqueda acotada: no se encontró un orden viable; revisar manualmente']:[])],estados};
 }
 function seleccionarCandidatos(negocios,{vendedor,hoy='',zona}={}){return negocios.filter(n=>!n.noContacto&&!n.archivado&&(!vendedor||!n.responsable||n.responsable===vendedor)&&(!zona||n.zona===zona)).map(n=>{let prioridad=0,razones=[];if(n.cita!=null||n.citaFecha){prioridad+=100;razones.push('Cita obligatoria');}if(n.seguimientoFecha&&n.seguimientoFecha<=hoy){prioridad+=60;razones.push('Seguimiento vencido');}if(n.compromisoPendiente){prioridad+=50;razones.push('Compromiso pendiente');}if(n.oportunidadAbierta){prioridad+=30;razones.push('Oportunidad abierta');}if(n.leTocaComprar===true&&n.consumoConfirmado===true){prioridad+=25;razones.push('Intervalo de compras confirmadas');}if(!n.visitasComerciales){prioridad+=10;razones.push('Sin visita comercial registrada');}return {...n,prioridad,razones};}).sort((a,b)=>b.prioridad-a.prioridad);}
 function planSemana(negocios,dias,opciones={}){const planes=dias.map(d=>({...d,paradas:[],razones:[]})),pendientes=[];for(const n of seleccionarCandidatos(negocios,opciones)){const obligatorio=!!n.citaFecha;const posibles=planes.filter(d=>(!obligatorio||d.fecha===n.citaFecha)&&d.paradas.length<Math.min(10,d.tope??opciones.tope??8));posibles.sort((a,b)=>Number(b.zona===n.zona)-Number(a.zona===n.zona)||a.paradas.length-b.paradas.length);if(posibles.length)posibles[0].paradas.push({...n,obligatoria:obligatorio});else pendientes.push({id:n.id,razon:obligatorio?'Cita sin día disponible o sin capacidad':'Sin capacidad semanal'});}return planes.map(d=>({...d,pendientes:pendientes.slice(),borrador:true}));}
 function sugerirDia(solicitud,planes){const ds=planes.filter(d=>!solicitud.fecha||d.fecha===solicitud.fecha).map(d=>({...d,puntos:Number(d.zona===solicitud.zona)*2+d.paradas.filter(p=>p.zona===solicitud.zona).length})).sort((a,b)=>b.puntos-a.puntos);return ds.length?{fecha:ds[0].fecha,razon:ds[0].puntos?'Ya hay ruta o solicitudes en esa zona':'Día disponible; requiere confirmación',automatico:false}:null;}
 function medirTramo(eventos){const ult=eventos.at(-1);if(ult?.tipo!=='LLEGADA')return null;const i=eventos.findLastIndex(e=>e.tipo==='SALIDA');if(i<0||eventos.slice(i+1,-1).some(e=>['PAUSA','DESVIO','LLEGADA','SALIDA'].includes(e.tipo)))return null;const sal=eventos[i],minutos=(Date.parse(ult.ts)-Date.parse(sal.ts))/60000;if(!Number.isFinite(minutos)||minutos<=0||sal.paradaId===ult.paradaId)return null;return {origenId:sal.paradaId,destinoId:ult.paradaId,minutos,ts:ult.ts,dia:sal.dia,franja:sal.franja,fuente:'MEDIDO'};}
 function proyectarRuta(eventos,tareas){const vistos=new Set(),map=new Map(tareas.map(t=>[t.id,{...t,estado:'PENDIENTE',pendiente:true}]));for(const e of eventos){if(vistos.has(e.id))continue;vistos.add(e.id);const t=map.get(e.tareaId);if(!t)continue;if(e.tipo==='RESULTADO'){const permitidos={ENTREGA:['ENTREGADA','PARCIAL','NO_ENTREGADA'],VISITA:['VISITADA','NO_ESTABA_COMPRADOR','NO_SE_PUDO_CONVERSAR','PIDIO_REGRESAR','NECESIDAD_IDENTIFICADA','PIDIO_COTIZACION','OFERTA_EN_EVALUACION','SIN_NECESIDAD_ACTUAL','RECHAZO_OFERTA','NO_CONTACTAR'],RECOLECCION:['RECOGIDA','PARCIAL','NO_RECOGIDA'],COBRANZA:['COBRO','COBRO_PARCIAL','PROMETIO_FECHA','NO_COBRO']};if(!permitidos[t.tipo]?.includes(e.resultado))throw Error('Resultado de tarea inválido');if(!['ENTREGA','VISITA','RECOLECCION','COBRANZA'].includes(t.tipo))throw Error('Tipo de tarea inválido');t.resultado=e.resultado;t.motivo=e.motivo||'';t.evidencia=e.evidencia;t.estado=t.tipo==='COBRANZA'&&['COBRO','COBRO_PARCIAL'].includes(e.resultado)?'POR_CONFIRMAR':e.resultado;t.pendiente=t.tipo==='COBRANZA'?t.estado!=='CONFIRMADO':['PARCIAL','NO_ENTREGADA','NO_RECOGIDA'].includes(e.resultado);}if(e.tipo==='PAGO_CONFIRMADO'&&e.publicadoERP===true&&t.tipo==='COBRANZA'){t.estado='CONFIRMADO';t.pendiente=false;}}return {tareas:[...map.values()],pendientes:[...map.values()].filter(t=>t.pendiente)};}
 function alrededorCita(cita,negocios,opciones={}){if(cita.noContacto)throw Error('Cita con no contacto');return [{...cita,obligatoria:true},...seleccionarCandidatos(negocios,opciones).filter(n=>n.id!==cita.id&&distancia(cita,n)<=(opciones.radioMetros??5000)).slice(0,Math.min(9,(opciones.tope??10)-1)).map(n=>({...n,obligatoria:false}))];}
function solicitudesPendientes(solicitudes,hoy){return solicitudes.filter(s=>!['ATENDIDA','CANCELADA'].includes(s.estado)).map(s=>({...s,vencida:!!s.fechaPedida&&s.fechaPedida<hoy,diasEsperando:Math.max(0,Math.floor((Date.parse(hoy)-Date.parse(s.fechaCaptura||s.fechaPedida))/86400000))})).sort((a,b)=>Number(b.vencida)-Number(a.vencida)||b.diasEsperando-a.diasEsperando);}
return {alrededorCita,solicitudesPendientes,distancia,crearMatriz,unirParadas,validarOrden,planificar,seleccionarCandidatos,planSemana,sugerirDia,medirTramo,proyectarRuta};
});


